#trigger: none  # Manual trigger only
trigger:
  branches:
    include:
      - main
  paths:
    include:
      - infrastructure/**

pr: none

name: AI Resource Provisioning Pipeline

parameters:
- name: azureServiceConnection
  type: string
  default: 'az2026connection'

variables:
  vmImageName: 'ubuntu-latest'
  resourceGroupName: 'rg-ai-experiments-resources'
  location: 'uk-south'
  bicepFile: './bicep/main.bicep'
  #bicepParamFile: './bicep/main.bicepparam'
  #csmParametersFile: './bicep/main.bicepparam'

pool:
  vmImage: $(vmImageName)


stages:
  - stage: Provision
    displayName: 'Provision infrastructure'
    jobs:
    - job: Provision
      displayName: 'Provision resources'
      strategy:
        runOnce:
          deploy:
            steps:

            - task: AzureCLI@2
              inputs:
                displayName: 'az version check'
                azureSubscription: '${{ parameters.azureServiceConnection }}'
                scriptType: bash
                scriptLocation: inlineScript
                useGlobalConfig: false
                inlineScript: |
                  az --version

            - task: AzureCLI@2
              displayName: 'Create resource group $(resourceGroupName)'
              condition: false
              inputs:
                azureSubscription: '${{ parameters.azureServiceConnection }}'
                scriptType: 'bash'
                scriptLocation: 'inlineScript'
                inlineScript: |
                  az group create --name $(resourceGroupName) --location $(location)

            - task: AzureCLI@2
              displayName: 'Deploy bicep template'
              inputs:
                azureSubscription: '${{ parameters.azureServiceConnection }}'
                scriptType: bash
                scriptLocation: inlineScript
                useGlobalConfig: false
                inlineScript: |
                  az deployment group create --resource-group  $(resourceGroupName) --template-file $(bicepFile) 

