# YAML syntax: https://learnxinyminutes.com/yaml/

#trigger: none  # Manual trigger only
trigger:
  branches:
    include:
      - main
  paths:
    include:
      - infrastructure/**

pr: none

name: AI Resource Provisioning Pipeline

parameters:
- name: azureServiceConnection
  type: string
  default: 'az2026connection'

variables:
  vmImageName: 'ubuntu-latest'

pool:
  vmImage: $(vmImageName)

stages:
  - stage: Provision
    displayName: 'Provision dev infrastructure'

    variables:
      - name: resourceGroupName 
        value: 'rg-ai-experiments-resources'
      - name: airesourceGroupName 
        value: 'rg-ai-experiments-openai-resources'
      - name: location
        value:  'uksouth'
      - name: aiResourcesLocation
        value:  'eastus2'
      - name: bicepFile
        value:  'infrastructure/bicep/main.bicep'
      # bicepParamFile: 'infrastructure//bicep/main.bicepparam'
      - name: aibicepFile
        value:  'infrastructure/bicep/az_openai.bicep'
      - group: ai-experiments-provisioning # Variable group containing secrets
          # Note: The variable group 'ai-experiments-provisioning' should contain the following variables:
            # deploySqlServer: true/false flag - whther to deploy SQL Server
            # sqlAdministratorLogin - username for SQL Server administrator
            # sqlAdministratorLoginPassword - password for SQL Server administrator

    jobs:
    - deployment: Provision
      displayName: 'Provision resources'
      environment: 'dev'
      strategy:
        runOnce:
          deploy:
            steps:

            - checkout: self # Explicit checkout because deployment job won't clone the repo by default

            - task: AzureCLI@2
              displayName: 'az version check'
              inputs:
                azureSubscription: '${{ parameters.azureServiceConnection }}'
                scriptType: bash
                scriptLocation: inlineScript
                useGlobalConfig: false
                inlineScript: |
                  az --version

            # - task: PowerShell@2
            #   displayName: List all Folders in $(System.DefaultWorkingDirectory)
            #   inputs:
            #     targetType: 'inline'
            #     pwsh: true
            #     script: |
            #       Get-ChildItem -path $(System.DefaultWorkingDirectory) -recurse | ForEach-Object { Write-Host $_.FullName }

            - task: AzureCLI@2
              displayName: 'Create resource group $(resourceGroupName)'
              inputs:
                azureSubscription: '${{ parameters.azureServiceConnection }}'
                scriptType: 'bash'
                scriptLocation: 'inlineScript'
                inlineScript: |
                  az group create --name $(resourceGroupName) --location $(location)

            - task: AzureCLI@2
              displayName: 'Deploy main bicep template'
              inputs:
                azureSubscription: '${{ parameters.azureServiceConnection }}'
                scriptType: bash
                scriptLocation: inlineScript
                useGlobalConfig: false
                inlineScript: >-
                  az deployment group create 
                    --resource-group  $(resourceGroupName) 
                    --template-file $(bicepFile) 
                    --parameters deploySqlServer=$(deploySqlServer) 
                                 sqlAdministratorPassword=$(sqlAdministratorPassword) 
                                 sqlAdministratorLogin=$(sqlAdministratorLogin)

            - task: AzureCLI@2
              displayName: 'Create AI resource group $(airesourceGroupName)'
              inputs:
                azureSubscription: '${{ parameters.azureServiceConnection }}'
                scriptType: 'bash'
                scriptLocation: 'inlineScript'
                inlineScript: |
                  az group create --name $(airesourceGroupName) --location $(aiResourcesLocation)

            - task: AzureCLI@2
              displayName: 'Deploy Azure OpenAI bicep template'
              inputs:
                azureSubscription: '${{ parameters.azureServiceConnection }}'
                scriptType: bash
                scriptLocation: inlineScript
                useGlobalConfig: false
                inlineScript: |
                  az deployment group create --resource-group  $(airesourceGroupName) --template-file $(aibicepFile) 
